### PR TITLE
FIX: use of TBB revealed bugs as pointed out in issue #238

### PR DESCRIPTION
**Pull request by SimonRit**

### CODE REVIEW

**Comment by kabcode** [comment]
Hi Simon,

when I try to build the ITKv5.0rc1 the branch of the RTK is automatically switch to the tag v2.0.0.
Did you move the tag to another commit? Or bump the RTK version in the remote module otherwise?

**Comment by SimonRit** [comment]
Hi,
Yes, you have to modify the RTK.remote.cmake file. Replace v2.0.0 by master or a specific tag you would like to build against. I don't think there is a better solution. I'll try to release a new RTK version soon and then I'll submit a patch to ITK.
Note that I have added a [fix](https://github.com/SimonRit/RTK/commit/4412d40025761cd5be4e34385143c11d11394206) to this PR.
Thanks,
Simon

**Comment by kabcode** [comment]
Hi,

i run the tests with the build descripted in #238 in RelWithDebInfo mode and attached the results here:
[ITK5withRTKmaster_RelWithDebInfo.txt](https://github.com/SimonRit/RTK/files/3065451/ITK5withRTKmaster_RelWithDebInfo.txt)
The RTK branch was changed as you wrote in the last post. 

Still the same nine tests are failing. Unfortunately, i am not very firm how to examine the tests in detail but if there is any output information that i can get for you i'll try.

**Comment by SimonRit** [comment]
Hi,
Thanks for testing. Weird... I don't know how you do this from MSVC but can you try to run the test with more log. From the command line, you can run `ctest -R "(rtk|RTK)" -VV`in your build directory.
I'll try to compile on Windows, I did the tests on Linux because my Windows box is a bit slow.
Simon

**Pull request merged**
