### PR TITLE
Fix link issue for gdcm use

### PR DESCRIPTION
**Pull request by FredChamp**
the FIND_PACKAGE(GDCM) was missing and the GDCM libraries were never linked to RTK libraries.

### CODE REVIEW

**Comment by SimonRit** [comment]
Hi,
I don't agree with this change. If GDCM is required, it should be compiled along with ITK and not externally. Can you let us know what's your configuration exactly?
Thanks,
Simon

**Comment by FredChamp** [comment]
We are using (fw4spl project) ITK with an external build of gdcm (Patched version) so we need to link with it
Even if RTK is compiled with a GDCM compiled along with ITK and not external, does my changes give a compilation issue ?

> Le 22 mars 2016 à 18:48, Simon Rit <notifications@github.com> a écrit :
> 
> Hi,
> I don't agree with this change. If GDCM is required, it should be compiled along with ITK and not externally. Can you let us know what's your configuration exactly?
> Thanks,
> Simon
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub <https://github.com/SimonRit/RTK/pull/22#issuecomment-199933407>


Frédéric CHAMP
Ingénieur de Recherche

frederic.champ@ircad.fr <mailto:frederic.champ@ircad.u-strasbg.fr>

 	 
http://www.ircad.fr/  <http://www.ircad.fr/>

Suivez l'IRCAD sur   <http://www.facebook.com/pages/IRCAD/193785273990141>
 
IRCAD France
Hôpitaux Universitaires - 1, place de l'Hôpital - 67091 Strasbourg Cedex - FRANCE

**Comment by FredChamp** [comment]
We are using (fw4spl project) ITK with an external build of gdcm (Patched version) so we need to link with it
Even if RTK is compiled with a GDCM compiled along with ITK and not external, does my changes give a compilation issue ?

**Comment by SimonRit** [comment]
Yes, I think it's a typical GDCM issue that I have seen before. With the internal ITK GDCM (default ITK compilation), everything works fine and compiles every night. I have had a lot of troubles with GDCM in the past and I've been told it's a gdcm issue, see, e.g., [https://cmake.org/pipermail/insight-users/2013-July/048397.html]. I would not add a required dependency to RTK but if you find a solution that can cope with your situation, I'm happy to accept a change.

**Comment by SimonRit** [comment]
Since there has not been any news in a while, I'm closing the pull request. We can reopen it if you have a new suggested change. Thanks,
Simon

**Pull request closed without merging**
