### PR TITLE
BUG: progress event attached to wrong ramp filter with cuda

### LINKED ISSUE #361: rtkramp segfaults when ran using CUDA
- `rtkramp -p . -r projection.mha -o /tmp/ramp.mha --hardware cpu` works fine;
- `rtkramp -p . -r projection.mha -o /tmp/ramp.mha --hardware cuda` segfaults, even though it should produce the same results given identical parameter.

I might misunderstand something... If not, I'll try to look into this issue.

### PR DESCRIPTION
**Pull request by SimonRit**
Fixes #361.

### CODE REVIEW

**Comment by SimonRit** [comment]
Can you review @acoussat? You have opened the issue and the bug comes from your code (I think).

**Comment by acoussat** [comment]
Sorry, yes indeed it looks like an error from my code. Your fix seems to partially correct the issue, but it unfortunately raises new problems. I ran the same tests than in #361 and here is what I observed:
- `rtkramp -p . -r projection.mha -o /tmp/ramp.mha --hardware cpu` works fine;
- `rtkramp -p . -r projection.mha -o /tmp/ramp.mha --hardware cuda` gives the following error:
```
itk::ExceptionObject (0x2b39a70)
Location: "unknown" 
File: /export/home/acoussat/Software/RTK-dev/src/include/rtkCudaFFTProjectionsConvolutionImageFilter.hxx
Line: 54
Description: itk::ERROR: itk::ERROR: CudaFFTRampImageFilter(0x247e2e0): CudaFFTProjectionsConvolutionImageFilter assumes that input requested and buffered regions are equal.
```
- `rtkramp -p . -r projection.mha -o /tmp/ramp.mha --hardware cpu -v` segfaults.

Concerning that last point, the error probably comes from my code so I'll have a look. Concerning the second point, I'm not sure.

**Comment by SimonRit** [comment]
>     * `rtkramp -p . -r projection.mha -o /tmp/ramp.mha --hardware cuda` gives the following error:
> 
> 
> ```
> itk::ExceptionObject (0x2b39a70)
> Location: "unknown" 
> File: /export/home/acoussat/Software/RTK-dev/src/include/rtkCudaFFTProjectionsConvolutionImageFilter.hxx
> Line: 54
> Description: itk::ERROR: itk::ERROR: CudaFFTRampImageFilter(0x247e2e0): CudaFFTProjectionsConvolutionImageFilter assumes that input requested and buffered regions are equal.
> ```

This is a limitation of the cuda version. You can circumvent it by using `--lowmem`or a larger `--subsetsize`.



>     * `rtkramp -p . -r projection.mha -o /tmp/ramp.mha --hardware cpu -v` segfaults.
> 
> 
> Concerning that last point, the error probably comes from my code so I'll have a look. Concerning the second point, I'm not sure.

I'm surprised because it's what I fixed

**Comment by acoussat** [comment]
Have you compiled RTK with `RTK_USE_CUDA` on? I am only getting the segfault with the `-v` flag when `RTK_USE_CUDA` is enabled. In order to fix this, I propose [this edit](https://github.com/acoussat/RTK/commit/bc507d9ef7ff512a54ae825aa8e38d32bfcd5bb5) to your fix (using the same logic as the previous `if` statements). Tell me if it looks fine to you, so that I can push it here.

On a side note, it looks like progress reporting is broken for ramp filter. Numerous trial-and-errors brought me to the conclusion that several edits on ITK's side broke our progress reporting system. I have only tested this on the ramp filter but other filters might be impacted as well. I haven't succeeded in fixing that. Have you heard about this? If not, I can open a new issue and give more details about what I observed and tried.

Thanks!

**Comment by SimonRit** [comment]
> Have you compiled RTK with `RTK_USE_CUDA` on?

Yes

> I am only getting the segfault with the `-v` flag when `RTK_USE_CUDA` is enabled. In order to fix this, I propose [this edit](https://github.com/acoussat/RTK/commit/bc507d9ef7ff512a54ae825aa8e38d32bfcd5bb5) to your fix (using the same logic as the previous `if` statements). Tell me if it looks fine to you, so that I can push it here.

Looks good, thanks. I guess I only tested the cuda version. I'll patch my PR.


> On a side note, it looks like progress reporting is broken for ramp filter. Numerous trial-and-errors brought me to the conclusion that several edits on ITK's side broke our progress reporting system. I have only tested this on the ramp filter but other filters might be impacted as well. I haven't succeeded in fixing that. Have you heard about this? If not, I can open a new issue and give more details about what I observed and tried.

I'm not aware of anything like this, no. Yes, please open an issue.

I'm not sure this actually solves #361 since it only corrects the problem with the `-v`option (as you experienced). Can you reproduce #361 without `-v`?
Thanks again,
Simon

**Pull request merged**
