### PR TITLE
DOC: first version of the installation instructions

### PR DESCRIPTION
**Pull request by SimonRit**
This is an attempt to fix issue #250 (sorry for the delay). @arobert01 @LucasGandel @codeling @NiklasFauth @acoussat can you review and comment before I merge? This file will replace the first section of the [wiki](http://wiki.openrtk.org).

### CODE REVIEW

**Comment by SimonRit** [comment]
Sorry, there was a problem with my commit. I don't know how I did this but it's now in the PR and the file is visible [here](https://github.com/SimonRit/RTK/blob/a72c00a4120431ee60f36db0adda3da886147357/documentation/INSTALLATION.md).

**Comment by arobert01** [comment]
Looks good to me

**Comment by codeling** [comment]
Haven't tried all details, but looks good to me!
The only thing I could think of that could be added is something regarding adding RTK to the COMPONENTS section of cmake's FindPackage call in an application using RTK (see https://github.com/SimonRit/RTK/issues/250#issuecomment-514516784)

**Comment by LucasGandel** [comment]
Looks good to me! 
+1 for adding a section about find_package as suggested by codeling

**Comment by acoussat** [comment]
Looks good to me! Nice that you list and explain the RTK-specific CMake options, I have learned something new along the way.

**Comment by SimonRit** [comment]
Thanks for your feedbacks and sorry for the delay. I have added a GettingStarted.md file and I have added a link to the line containing find_package of the FirstReconstruction CMakeLists.txt. It's now merged.

**Pull request merged**
