### PR TITLE
Fix find module library name

### PR DESCRIPTION
**Pull request by hjmjohnson**

### CODE REVIEW

**Comment by hjmjohnson** [comment]
Need to change the name of the library.

**Comment by SimonRit** [comment]
Thanks but why is this a need?

**Comment by hjmjohnson** [comment]
I'm building a tool that depends on RTK.  That tool uses "find_package(RTK)" to identify and use the "RTK_LIBRARIES" variable to link against.

**Comment by hjmjohnson** [comment]
The library name that is currently generated is "libitkRTK-5.0.a" when built against ITK v5, and "libitkRTK-4.13.a" when built against ITK 4.13.

Hans

**Comment by hjmjohnson** [comment]
Can this please be incorporated?

The find_package fails without this patch because the name of the library that is searched for is wrong.

Hans

**Comment by SimonRit** [comment]
@LucasGandel There is indeed a problem with the library name. Currently, on RTK-ExternalModule or with this patch, I cannot compile on MacOS with dynamic libraries. Can you try to fix this?

**Comment by LucasGandel** [comment]
@SimonRit I'll try to reproduce on MacOS and have a look at AppVeyor failures.

**Comment by hjmjohnson** [comment]
Addressed in #165

**Pull request closed without merging**
