### PR TITLE
BugFix: changed AddProjections to AddProjectionsInRadians in rtkDigisensGeometryReader.cxx

### PR DESCRIPTION
**Pull request by cdeepakroy**
AddProjection() expects all angles to be in degrees. The [code](https://github.com/SimonRit/RTK/pull/19/files#diff-3fd809ed536af9fbddb42d5b75126856R114) in rtkDigisensGeometryReader.cxx erroneously supplied angles in radians to this function.

@SimonRit If you think this fix is ok, i can modify the test file on MIDAS as well to make the test pass.

### CODE REVIEW

**Comment by SimonRit** [comment]
Sorry about that... Yes please, send a new test file by email and I'll merge the whole thing when the tests will pass.
Thanks a lot for your contribution!

**Comment by SimonRit** [comment]
Hi Deepak, what's the status of this contribution? Do you confirm that the angles are in radians and should I just update the baseline file for the test?

**Comment by cdeepakroy** [comment]
@SimonRit sorry for letting this linger for so long. Yes the angles are in radians and the change from the call to AddProjection and AddProjectionInRadians is correct. We just need to change the test file to make it pass. Please do it if you can. If not, I will try to do it this weekend.

**Comment by SimonRit** [comment]
Done, thanks again for the contribution.
Simon

**Pull request merged**
