### PR TITLE
Update lu solve

### PR DESCRIPTION
**Pull request by hjmjohnson**

### CODE REVIEW

**Comment by hjmjohnson** [comment]
Rebasing on RTK-ExternalModule

**Comment by hjmjohnson** [comment]
@SimonRit   This patch set fixes many compiler warnings that were contaminating the build process and masking other more pressing problems.  It would wonderful if there were a mechanism to push these changes upstream to lp_solve, but I could not find a way to make such a pull request.

**Comment by hjmjohnson** [comment]
@SimonRit Do you have any interest in merging this code cleanup?

**Comment by SimonRit** [comment]
Yes, thanks and sorry for not merging it immediately. I'll cherry-pick the changes in master, I don't see any good reason to not have it.

**Pull request merged**
