### PR TITLE
FIX Change from std::random_shuffle to std::shuffle

### PR DESCRIPTION
**Pull request by kabcode**
with C++17 the std::random_shuffle is deleted. This function is replaced by std::shuffle that does the same with the option for a different random generator.

### CODE REVIEW

**Comment by kabcode** [comment]
ci/circleci stopped building due to the following error:

> Building CXX object CMakeFiles/RTKHeaderTest6.dir/test/RTKHeaderTest6.cxx.o
> In file included from /root/RTK/include/rtkConjugateGradientImageFilter.h:28:0,
>                  from /root/RTK/include/rtkConjugateGradientConeBeamReconstructionFilter.h:25,
>                  from /root/RTK/include/rtkConjugateGradientConeBeamReconstructionFilter.hxx:22,
>                  from /root/RTK-build/test/RTKHeaderTest6.cxx:52:
> /root/RTK/include/rtkConjugateGradientGetR_kPlusOneImageFilter.h:24:24: fatal error: itkBarrier.h: No such file or directory
>  #include <itkBarrier.h>
>                         ^
> compilation terminated.

`itk::Barrier` is now deprecated. I do not know what it is doing in this particular case.

TravisCI uses ITK4.13 and AppVeyor uses ITK4.12. CircleCI runs a more recent version of ITK5.

**Comment by SimonRit** [comment]
Thanks, that's great. I honestly don't understand what's going on with CircleCI since Barriers have been remove a while ago. Before I try to address this, one comment: do you mind renaming m_dre with m_DefaultRandomEngine? That will be more compliant with the [ITK coding style](https://itk.org/Wiki/ITK/Coding_Style_Guide):      

> Names are generally spelled out; use of abbreviations is discouraged. (Abbreviation are allowable when in common use, and should be uppercase as in RGB.) While this does result in long names, it self-documents the code. 

Please also amend the commit message and refer to issue #251. Thanks a lot for all this!

**Review by SimonRit — COMMENTED** [review]
This is not good because we still want to keep backward compatibility until ITK v4.12... I think commit db27af0 is better but it seems you need to pull master?

**Comment by SimonRit** [comment]
Thanks again for your efforts. So 13cbd6c can be dropped I believe if you pull master and we should still address the style and the commit message as pointed out in my comment 13 days ago. I can finalize this PR if you prefer?

**Comment by kabcode** [comment]
Hi Simon, 
sorry for being unresponsive. I am currently very busy with some other project. 
Please go ahead and finalize the PR. I am sorry to delay the process. 
I was completly dropping support for ITKv4 but I can do this because no one is depending on my code.

**Comment by SimonRit** [comment]
Superseded by  #255

**Pull request closed without merging**
