### PR TITLE
COMP: Support multiple find_package(Gengetopt)

### PR DESCRIPTION
**Pull request by finetjul**
The following should not produce any error:
```
cmake_minimum_required(VERSION 3.15)

project(testFindGengetopt)

list(APPEND CMAKE_MODULE_PATH "${RTK_SOURCE_DIR}/cmake")
include("${RTK_SOURCE_DIR}/cmake/rtkCompilerFlags.cmake")
find_package(Gengetopt REQUIRED)
find_package(Gengetopt REQUIRED)
```

### CODE REVIEW

**Comment by SimonRit** [comment]
Thanks but 5081577 does not seem to work see e.g. [here](https://dev.azure.com/simonrit/RTK/_build/results?buildId=557&view=logs&j=eafb87dd-1923-5b11-0b2b-e4ed58eef8aa&t=c476e6ed-da0f-5921-29b4-af92b6bde1f3&l=305). Should it be ` CheckCXXSourceCompiles`? See [here](https://cmake.org/cmake/help/latest/module/CheckCXXCompilerFlag.html?highlight=check_cxx_compiler_flag).

**Comment by finetjul** [comment]
I do not understand why it fails, I just tried (granted on Windows only) with `CMake 3.17` and `include(CheckCxxCompilerFlag)` works fine.

**Comment by finetjul** [comment]
Thanks @LucasGandel for finding the typo.

**Comment by finetjul** [comment]
@SimonRit does it look good to you ? Can it be merged ?

**Comment by SimonRit** [comment]
Yes! Thanks!

**Pull request merged**
