### PR TITLE
ENH: ProjectionsReader: support RawImageIO

### LINKED ISSUE #469: ProjectionsReader support RawImageIO
Thanks a lot for this nice package.
Here is a feature suggestion:

It would be useful if the class rtk::ProjectionsReader supported reading out raw data files, in the same way than itk::ImageSeriesReader does.

```
    using ImageIOType = itk::RawImageIO<unsigned short, 3>;
    using ImageType = itk::Image<unsigned short, 3>;
    ImageIOType::Pointer io = ImageIOType::New();
    io->SetDimensions(...);
    io->SetOrigin(...);
    io->SetSpacing(...);
    io->SetByteOrderToLittleEndian();
    using ReaderType = itk::ImageSeriesReader< ImageType >;
    ReaderType::Pointer reader = ReaderType::New();
    reader->SetImageIO( io );
    reader->SetFileNames( nameGenerator->GetFileNames() );
    reader->Update();
```

Currently, this cannot be done via rtk::ProjectionsReader, as it is missing the SetImageIO functionality.

### PR DESCRIPTION
**Pull request by ferdymercury**
CopyPaste SetImageIO function from ImageSeriesFileReader to ProjectionsReader

Fixes https://github.com/SimonRit/RTK/issues/469

### CODE REVIEW

**Comment by ferdymercury** [comment]
With the reproducer I sent you per e-mail, I still get one error, and I am unsure what the best way would be to solve it.

`ITK ERROR: Can not use I0 in LUTbasedVariableI0RawToAttenuationImageFilter with this input (not implemented)`

Also, the input images are unsigned short, but if the logarithm is calculated, the output should be float rather than ints, right? Can the output of ProjReader be of a different type than the input?

**Comment by SimonRit** [comment]
Yes, the input is often different from the output which is always float or double. Input should be integers for using the I0 option.
The ITK error here is caused by the current test [here](https://github.com/SimonRit/RTK/pull/470/files#diff-df29114932beecd7236503c98a20b751da3293158c12332be9a45c66adf5d362R172) that sets everything up the first time. It never enters this block with your current modification...
Should I try to find a solution or you'll handle it?

**Comment by ferdymercury** [comment]
> Should I try to find a solution or you'll handle it?

Thanks for the reply. I can try to find a solution, however I will need some guidance, as it is my first time using RTK. If it is less work for you to implement yourself than to guide me, then please feel free to do it yourself, much appreciated.

Here my questions:

```
imageIO->SetFileName(m_FileNames[0].c_str());
imageIO->ReadImageInformation();
```
I believe these two lines above won't be needed for RawImageIO, right ?

And what about the name of the class, is it called "RawImageIO" instead of "EdfImageIO"?, which means that I have to create a similar if-else block below?

```
if ((!strcmp(imageIO->GetNameOfClass(), "EdfImageIO") &&
         imageIO->GetComponentType() == itk::ImageIOBase::IOComponentEnum::USHORT) ||
        !strcmp(imageIO->GetNameOfClass(), "XRadImageIO"))
    {

```

Is the ChangeInfoFilter necessary also for RawImageIO ? What is it doing?

Do I need to create a "RawToAttenuation" Filter analogously to "EdfRawToAttenuation" ? In what file?

```
using RawFilterType = rtk::EdfRawToAttenuationImageFilter<InputImageType, OutputImageType>;
typename RawFilterType::Pointer rawFilter = RawFilterType::New();
m_RawToAttenuationFilter = rawFilter;
```

Thanks in advance.

**Comment by SimonRit** [comment]
> I believe these two lines above won't be needed for RawImageIO, right ?

I'm actually not sure but I guess not since there is no information to read, all is set manually.

> And what about the name of the class, is it called "RawImageIO" instead of "EdfImageIO"?, which means that I have to create a similar if-else block below?

No need to handle this. Since your pixel type is unsigned short, you want to go in [this block](https://github.com/SimonRit/RTK/blob/08fd9ad16fda710e1e3153ebb9a3ae37cf6f2578/include/rtkProjectionsReader.hxx#L288). So you only need to address the fact that m_ImageIO always equals imageIO, maybe using the boolean you have defined.

> Do I need to create a "RawToAttenuation" Filter analogously to "EdfRawToAttenuation" ? In what file?

No, nothing else to develop. If I remove the test `if (m_ImageIO != imageIO)`, everything already works but it's better to make sure that you enter this block once only.

**Comment by ferdymercury** [comment]
Thanks Simon, I did as you suggested (see latest commit).

Now I do not get any error. However, my reconstructed image is completely empty (all zeroes).

I tried also calling ReadImageInformation (removing the if-check), but result is the same. So I am a bit lost again. I am not sure whether the Spacing and Origin of RawImageIO are being forwarded correctly to the ProjectionsReader class.

**Comment by ferdymercury** [comment]
Ok, changing the output ImageType to float makes things better, now it is not all zero. Closing in favor of #472. Thanks!

**Pull request closed without merging**
