### PR TITLE
COMP: Declare ITKCudaCommon as an IMPORTED library in ITKTargets.cmake

### PR DESCRIPTION
**Pull request by finetjul**
See #360

### CODE REVIEW

**Comment by finetjul** [comment]
@LucasGandel

**Comment by SimonRit** [comment]
Do you think that the [failing builds](https://my.cdash.org/index.php?project=RTK&date=2020-07-06) are related? I'm lost!

**Comment by SimonRit** [comment]
Closing and reopening to relaunch checks

**Comment by SimonRit** [comment]
Closing, as ITKCudaCommon has been moved to a separate repository, https://github.com/RTKConsortium/ITKCudaCommon.

**Pull request closed without merging**
