### PR TITLE
ENH: upgrade CI for python packages to 5.2rc01

### PR DESCRIPTION
**Pull request by SimonRit**

### CODE REVIEW

**Review by thewtex — APPROVED** [review]

**Comment by thewtex** [comment]
@SimonRit I see the artifact download error in `Build, test, package / publish-python-packages-to-pypi (push) `, but I do not see the source of this -- any pointers?

**Comment by SimonRit** [comment]
> @SimonRit I see the artifact download error in `Build, test, package / publish-python-packages-to-pypi (push) `, but I do not see the source of this -- any pointers?

No. I'm guessing it's a github issue which wasn't there in the [previous compilation](https://github.com/SimonRit/RTK/actions/runs/476152100). I only amended the commit and forced push to modify setup.py following InsightSoftwareConsortium/ITKModuleTemplate@ddf8381339ca92143b4e39ae6e30d252f58f6e7b. I could relaunch the compilation but I will not merge anyway because the produced packages don't work, see InsightSoftwareConsortium/ITK#2064. Any clue how to solve this issue? It's been there for a long time but I have no idea how to solve this...

**Comment by thewtex** [comment]
@SimonRit yes, addressed in https://github.com/InsightSoftwareConsortium/ITK/pull/2258

**Comment by SimonRit** [comment]
Superseded by #403.

**Pull request closed without merging**
