### PR TITLE
Fix compilation error about floor on cu files

### PR DESCRIPTION
**Pull request by tsadakane**
Hello. Thanks for this great project. I tried to compile RTK independently on ITK. The following modification was necessary.

# summary
Fix compilation error with VS 2019 (16.9.5) and CUDA 11.1

# Errors
The compilation fails on VS 2019 (16.9.5) with the following errors:

```
8>.../RTK/src/rtkCudaForwardWarpImageFilter.cu(193): error : calling a __host__ function("__floorf") from a __global__ function("linearSplat_3Dgrid") is not allowed
8>
8>.../RTK/src/rtkCudaForwardWarpImageFilter.cu(193): error : identifier "__floorf" is undefined in device code
8>
8>.../RTK/src/rtkCudaForwardWarpImageFilter.cu(194): error : calling a __host__ function("__floorf") from a __global__ function("linearSplat_3Dgrid") is not allowed
8>
8>.../RTK/src/rtkCudaForwardWarpImageFilter.cu(194): error : identifier "__floorf" is undefined in device code
8>
8>.../RTK/src/rtkCudaForwardWarpImageFilter.cu(195): error : calling a __host__ function("__floorf") from a __global__ function("linearSplat_3Dgrid") is not allowed
8>
8>.../RTK/src/rtkCudaForwardWarpImageFilter.cu(195): error : identifier "__floorf" is undefined in device code
8>
8>6 errors detected in the compilation of ".../RTK/src/rtkCudaForwardWarpImageFilter.cu".
```
and 
```
5>.../RTK/src/rtkCudaRayCastBackProjectionImageFilter.cu(218): error : calling a __host__ function("__floorf") from a __global__ function("kernel_ray_cast_back_project") is not allowed
5>
5>.../RTK/src/rtkCudaRayCastBackProjectionImageFilter.cu(218): error : identifier "__floorf" is undefined in device code
5>
5>.../RTK/src/rtkCudaRayCastBackProjectionImageFilter.cu(219): error : calling a __host__ function("__floorf") from a __global__ function("kernel_ray_cast_back_project") is not allowed
5>
5>.../RTK/src/rtkCudaRayCastBackProjectionImageFilter.cu(219): error : identifier "__floorf" is undefined in device code
5>
5>.../RTK/src/rtkCudaRayCastBackProjectionImageFilter.cu(220): error : calling a __host__ function("__floorf") from a __global__ function("kernel_ray_cast_back_project") is not allowed
5>
5>.../RTK/src/rtkCudaRayCastBackProjectionImageFilter.cu(220): error : identifier "__floorf" is undefined in device code
5>
5>6 errors detected in the compilation of ".../RTK/src/rtkCudaRayCastBackProjectionImageFilter.cu".
```
# Change

`floor` => `floorf`

# Comment
This might have been occured since VS2019 16.9.1.
Similar (same?) issue can be found here: https://github.com/CERN/TIGRE/pull/264

### CODE REVIEW

**Comment by SimonRit** [comment]
Thanks, looks good. Can you please modify the commit message with the prefix COMP:, following the [ITK rules](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md)?

**Comment by tsadakane** [comment]
Thank you for reviewing my PR. I modified the commit message, but I could not help an unexpected commit being added to the history. Sorry for making a PR with such annoying logs for such a well organized project. Shall I re-create the PR?

**Comment by SimonRit** [comment]
That should not be needed. You an try instead 
```
git checkout fix_compilation-error-vs2019-floor-cu-files
git rebase master
git push -f
```
which should remove the extra two commits. Thanks for the work!

**Comment by SimonRit** [comment]
Thanks @tsadakane!

**Comment by tsadakane** [comment]
Thank you for accepting my PR, and your advices.

**Pull request merged**
