### PR TITLE
ENH: Change default value of OSEM regularization to 0

### PR DESCRIPTION
**Pull request by arobert01**

### CODE REVIEW

**Comment by SimonRit** [comment]
Do you now think it's better like this?

**Comment by arobert01** [comment]
Yes, on second thought, I think it's better to have the "classical" behavior of the MLEM/OSEM algorithm by default. Furthermore, the weight of the regularization depend of the distribution that one want to reconstruct so it would be better to let the user choose this value if needed.

**Comment by SimonRit** [comment]
One test is now failing so the regularization parameter should be set in it?
https://my.cdash.org/index.php?project=RTK

**Comment by arobert01** [comment]
Sorry I didn't see the fail. Yes we could add the regularization parameter in the test or change a little bit the threshold of the MSE for the test (the MSE is 451.23 instead of 450). What do you think is better ?

**Comment by SimonRit** [comment]
No preference.

**Pull request merged**
